GET http://localhost:3000/users

###

GET http://localhost:3000/users?limit=2&offset=2&order=oldest

###

GET http://localhost:3000/users/70e1e61d-f2ae-4d7d-bf8f-d65eafdb6a45

###

GET http://localhost:3000/users/70e1e61d-f2ae-4d7d-bf8f-d65eafdb6a45/orders

###
GET http://localhost:3000/users/70e1e61d-f2ae-4d7d-bf8f-d65eafdb6a45/saved-products

###


POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "yjkim@example.com", 
  "firstName": "유진",
  "lastName": "김",
  "address": "충청북도 청주시 북문로 210번길 5",
  "userPreference": {
    "receiveEmail": false
  }
}
###

PATCH http://localhost:3000/users/f9d701e6-1610-40d5-81a3-6854289ec8c6
Content-Type: application/json

{
  "address": "서울특별시 강남구 무실로 234번길 45-6"
}

###

DELETE http://localhost:3000/users/73cb9639-d8b7-4f11-9a62-53f4187f3f11

###
POST http://localhost:3000/users/70e1e61d-f2ae-4d7d-bf8f-d65eafdb6a45/saved-products
Content-Type: application/json

{
  "productId": "d9e3f6ae-04e5-4a7b-8c7c-2d582af08489"
}